version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.17.0
    commands:
      - echo Installing dependencies...
      - npm install --legacy-peer-deps
      - npm install -g npm@latest

  pre_build:
    commands:
      - echo Installing additional dependencies...
      - npm install @babel/plugin-proposal-private-property-in-object --save-dev

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ s3://heathcare-cicd-123 --delete

artifacts:
  files:
    - '**/*'
  base-directory: build