version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ s3://heathcare-cicd-123 --delete

artifacts:
  files:
    - '**/*'
  base-directory: build 